export const layer1 = [
  { row: 0, col: 0 },
  { row: 0, col: 1 },
  { row: 0, col: 2 },
  { row: 0, col: 3 },
  { row: 0, col: 4 },
  { row: 0, col: 5 },
  { row: 0, col: 6 },
  { row: 1, col: 0 },
  { row: 1, col: 6 },
  { row: 2, col: 0 },
  { row: 2, col: 6 },
  { row: 3, col: 0 },
  { row: 3, col: 6 },
  { row: 4, col: 0 },
  { row: 4, col: 6 },
  { row: 5, col: 0 },
  { row: 5, col: 6 },
  { row: 6, col: 0 },
  { row: 6, col: 1 },
  { row: 6, col: 2 },
  { row: 6, col: 3 },
  { row: 6, col: 4 },
  { row: 6, col: 5 },
  { row: 6, col: 6 },
];

export const layer2 = [
  { row: 1, col: 1 },
  { row: 1, col: 2 },
  { row: 1, col: 3 },
  { row: 1, col: 4 },
  { row: 1, col: 5 },
  { row: 2, col: 1 },
  { row: 2, col: 5 },
  { row: 3, col: 1 },
  { row: 3, col: 5 },
  { row: 4, col: 1 },
  { row: 4, col: 5 },
  { row: 5, col: 1 },
  { row: 5, col: 2 },
  { row: 5, col: 3 },
  { row: 5, col: 4 },
  { row: 5, col: 5 },
];

export const layer3 = [
  { row: 2, col: 2 },
  { row: 2, col: 3 },
  { row: 2, col: 4 },
  { row: 3, col: 2 },
  { row: 3, col: 4 },
  { row: 4, col: 2 },
  { row: 4, col: 3 },
  { row: 4, col: 4 },
];

export const layer4 = [{ row: 3, col: 3 }];
